node {
  def golangkafkaImage

  stage('Git Pull') {
    git url: 'https://github.com/joshchu00/docker.git', branch: 'master'
  }
  stage('Docker Build') {
    docker.withTool('docker-latest') {
      golangkafkaImage = docker.build('docker.io/joshchu00/golang-kafka:1.11-alpine', 'golang-kafka')
    }
  }
  stage('Docker Push') {
    docker.withTool('docker-latest') {
      docker.withRegistry('', 'DockerHub') {
        golangkafkaImage.push()
      }
    }
  }
}
